# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9652e4179af2cf2474aa167c4d31ca7a9c6c0931e2b4296f7efea603da8938b626a19af72d2c94198a76bb424bba548b2cc03af043f4237914baeac11e3e70d

test:
  secret_key_base: c16179149daf875ef556d22515b52aa0f9e85a9a2fc293779fcc521b6577e827ee224bad063bb8df0ec32a6a5d5f3224a47e2539e58565d32753c06c75394c48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
